### ISSUE TITLE
코드 내에서 오류가 있습니다.

### ISSUE THREAD

**Issue by entry62045** [simonj-entry/StrongBlock#1]
안녕하세요. 62045입니다.
코드에 오류가 있어서 알려드리겠습니다.
![image](https://user-images.githubusercontent.com/77736636/106715626-acebb280-6640-11eb-94f9-dc389209c8d0.png)

**Comment by simonj-entry** [comment]
어떻게 해야 오류가 고쳐집니까?

**Comment by entry62045** [comment]
아래 simonj님의 코드 기반으로 제가 수정하여 오류 해결된 코드입니다. 
여러 개의 코드 제작시 뒤에 다른 코드 추가하신다면 코드 블럭 맨 끝에 반점 붙여주세요.
맨 마지막 블럭 코드에는 붙이지 않습니다.
그리고 괄호는 끝부분도 추가해주세요. 에디터를 사용하시면 괄호 시작과 끝을 알 수 있고 자동으로 완성해줍니다.
아 그리고 코드 525줄에 name 부분을 제가 실수로 중복되게 firsttext로 해놨는데 그거 다른 걸로 바꾸시면됩니다.

[block.txt](https://github.com/simonj-entry/StrongBlock/files/5918915/block.txt)

**Comment by simonj-entry** [comment]
코드 내의 오류는 어떤 프로그램을 사용하여 어떻게 찾아요?

**Comment by entry62045** [comment]
저는 개인적으로 Visual Studio Code를 추천합니다.
GitHub 저장소와 연결되고 GitHub 저장소에 폴더를 만들 수 있습니다.

**Comment by simonj-entry** [comment]
혹시 다운로드링크 남겨주실수 있나요?

**Comment by entry62045** [comment]
https://code.visualstudio.com
